baseurl = "https://www.r-podcast.org/"
relativeurls = true
languageCode = "en-us"
title = "The R-Podcast"
theme = "castanet"
#googleAnalytics = "UA-123-45"
disqusShortname = "r-podcast"
themesdir = "themes"
metaDataFormat = "yaml"
PaginatePath = "articles"

[permalinks]
	about = "/:filename/"
	contact = "/:filename/"
	subscribe = "/:filename/"
	guests = "/:filename/"
	resources = "/:filename/"
	articles = "/articles/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# SectionPagesMenu = "Main"
# About section of menu
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Subscribe"
    identifier = "subscribe"
    url = "/subscribe"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Guests"
		identifier = "guests"
		url = "/guests"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "/resources"
    
[[Menu.Main]]
    name = "Articles"
    identifier = "articles"
    url = "/articles"

[params]
site_theme = "blue"
site_layout = "row"
enable_jumbo = "false"
# about_logo = ""  # path to image file within hugo dir
copyright_notice = "The R-Podcast is licensed under a Creative Commons Attribution 4.0 International License.  Web site powered by [hugo](https://gohugo.io/) and [blogdown](https://github.com/rstudio/blogdown) all created within [R](https://www.r-project.org/)"
soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
itunes_subscribe = "https://itunes.apple.com/us/podcast/the-r-podcast/id1140581792"
pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
mailchimp_subscribe = "//r-podcast.us14.list-manage.com/subscribe/post?u=060990021bb38f2dbcc6a55ac&amp;id=6aca215b46"
description = "Giving practical advice on how to use R for powerful and innovative data analyses."
media_prefix = "https://aphid.fireside.fm/d/1437767933/487fd4f7-8859-4de4-98de-25634d400177/"
  [params.feed]
    feed_copyright = "Copyright 2017 Eric Nantz" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "" #no markdown or HTML
    itunes_author = "Eric Nantz" #no markdown or HTML
    itunes_summary = "The R-Podcast is a podcast for both new and experienced R users who want to learn more about using R to conduct innovative data analyses." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Eric Nantz"
    itunes_owner_email = "theRcast@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "http://i.imgur.com/Mr70QS9.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    #itunes_first_sub_category = "Software How-To"
    #itunes_second_sub_category = "Tech News"

  [params.social]
    github = "thercast"
		gitlab = "rpodcast"
    twitter = "thercast"
    twitter_domain = "r-podcast.org" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "111193531932434833188"
    youtube = "TheRPodcast"

  [params.authors]
    [params.authors.Eric]
      name	= "Eric Nantz"
      thumbnail = "http://i.imgur.com/Mr70QS9.png"
      bio = "The host of the R-Podcast is Eric Nantz, a statistician working in the life sciences industry who has been using R since 2004.  Eric quickly developed a passion for using and learning more about R due in large part to the brilliant and exciting R community and its free and open source heritage, much like his favorite operating system Linux.  Currently he is running a mix of various linux distributions such as Arch, Ubuntu, and CentOS on both his local computers and virtual servers hosted on [Digital Ocean](https://www.digitalocean.com), each running R of course!"
      [params.authors.Eric.social]
        github = "thercast"
        twitter = "thercast"
        #linkedin = "
        #homepage = ""

	[params.links]
		[params.links.twitter]
			name = "@theRcast on Twitter"
			url = "https://twitter.com/theRcast"
		[params.links.rweekly]
			name = "R-Weekly"
			url = "https://rweekly.org"
		[params.links.rbloggers]
			name = "R-Bloggers"
			url = "http://www.r-bloggers.com"
		[params.links.rstatistics]
			name = "R-Statistics Blog"
			url = "http://www.r-statistics.com"
		[params.links.rusers]
			name = "R-Users"
			url = "http://www.r-users.com"
		[params.links.rstudioblog]
			name = "RStudio Blog"
			url = "https://blog.rstudio.com"
		[params.links.rviews]
			name = "R-Views"
			url = "https://www.rstudio.com/rviews.com"
		[params.links.metacran]
			name = "METACRAN"
			url = "https://www.r-pkg.org/"
		[params.links.datacamp]
			name = "DataCamp"
			url = "https://www.datacamp.com"
